### PR TITLE
Add root check, remove hardcoded vm1.log

### PR DESCRIPTION
**Pull request by ShoelaceMan**

### CODE REVIEW

**Review by JeremiahSecrist — COMMENTED** [review]
Doesn't this undermined the minimum permission thing you mentioned before? we go from sudo in only one location to the entire script.

**Review by JeremiahSecrist — APPROVED** [review]
Was testing it and forgot to fix that aspect of it.

**Review by JeremiahSecrist — APPROVED** [review]

**Comment by ShoelaceMan** [comment]
Partly, but in this case I'd rather have the ability to automate before using sudo and requiring a password prompt. At the moment, that portion of the script returns nothing for me, and I think there would be a way to get the log in a more accurate way, I didn't look into it tonight, but the domain is able to he selected by pressing the number assigned to it in virsh list, but it fails to get the log because of the difference in naming conventions, I can look more into it later, I'd you'd like me to find out a way to do so without root, and I a way that's typo proof

**Comment by JeremiahSecrist** [comment]
I'll dig around as well and report what I find as well.

**Pull request merged**
